# Dependabot setup — this file tells GitHub how to check for dependency updates.

version: 2  # Using the current Dependabot config version.

updates:
  # This section keeps our Ruby gems up to date.
  - package-ecosystem: bundler
    directory: "/"               # The Gemfile is in the root folder.
    schedule:
      interval: daily            # Dependabot checks for updates every day.
    open-pull-requests-limit: 10 # Don’t open more than 10 PRs at once.

  # This one does the same for our GitHub Actions workflows.
  - package-ecosystem: github-actions
    directory: "/"               # Looks at .github/workflows in the root.
    schedule:
      interval: daily            # Also checks daily for new Action versions.
    open-pull-requests-limit: 10 # Cap it at 10 open PRs here too.