# Default cache configuration
default: &default
  store_options:
    # Maximum size of the cache
    max_size: <%= 256.megabytes %>
    # Namespace by Rails environment
    namespace: <%= Rails.env %>
    # Optional: limit cache age to enforce retention policies
    # max_age: <%= 60.days.to_i %>

development:
  <<: *default

test:
  <<: *default

production:
  # Use a database-backed cache in production
  database: cache
  <<: *default
