# PostgreSQL database configuration for Rails
# Uses the pg gem (install via `gem install pg`)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Alpha1one!      # In production, use ENV variables instead
  host: 127.0.0.1

development:
  <<: *default
  database: dandelion_warehouse_development
  username: postgres
  password: Alpha1one!
  host: localhost

test:
  <<: *default
  database: dandelion_warehouse_test
  username: postgres
  password: Alpha1one!
  host: localhost

production:
  primary: &primary_production
    <<: *default
    database: dandelion_warehouse_production
    username: dandelion_warehouse
    password: <%= ENV["DANDELION_WAREHOUSE_DATABASE_PASSWORD"] %>

  # Separate databases for caching, queues, and Action Cable
  cache:
    <<: *primary_production
    database: dandelion_warehouse_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: dandelion_warehouse_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: dandelion_warehouse_production_cable
    migrations_paths: db/cable_migrate
