# Solid Queue configuration for job processing

default: &default
  # Dispatcher settings
  dispatchers:
    - polling_interval: 1
      batch_size: 500

  # Worker settings
  workers:
    - queues: "*"              # Listen to all queues
      threads: 3               # Threads per worker
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1    # How often workers check for jobs

# Environment-specific configs
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
